- name: install ssh package
  ansible.builtin.apt:
    name: openssh-server
    state: present
  become: true

- name: create /run/sshd directory
  ansible.builtin.file:
    path: /run/sshd
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
