- name: include os specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yaml"

- name: include debian specific tasks
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_os_family | lower == "debian"

- name: include redhat specific tasks
  ansible.builtin.include_tasks: redhat.yaml
  when: ansible_os_family | lower == "redhat"

- name: create jenkins group
  ansible.builtin.group:
    name: jenkins
    state: present
    system: true
  become: true

- name: create jenkins user
  ansible.builtin.user:
    name: jenkins
    state: present
    group: jenkins
    create_home: false
    shell: /usr/sbin/nologin
    system: true
  become: true

- name: create jenkins home directory
  ansible.builtin.file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
  become: true

- name: create jenkins working directory
  ansible.builtin.file:
    path: "{{ jenkins_working_dir }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
  become: true

- name: create custom init scripts directory
  ansible.builtin.file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
  become: true

- name: render systemd service file
  ansible.builtin.template:
    src: jenkins.service.j2
    dest: "{{ __jenkins_service_dir }}/jenkins.service"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - reload systemd
    - restart service

- name: ensure service is started and enabled
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true
  become: true

- name: read initial admin password from the file
  when: jenkins_show_initial_admin_password
  block:
    - name: get content of initialAdminPassword file
      ansible.builtin.slurp:
        src: "{{ jenkins_home }}/secrets/initialAdminPassword"
      become: true
      register: jenkins_initial_admin_password

    - name: show initial admin password
      ansible.builtin.debug:
        msg: "{{ jenkins_initial_admin_password.content | b64decode | trim }}"

- name: flush handlers
  ansible.builtin.meta: flush_handlers
