dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    image: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    # dockerfile: ../common/Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host  # https://www.jeffgeerling.com/blog/2022/docker-and-systemd-getting-rid-dreaded-failed-connect-bus-error
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:6379:6379/tcp
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
verifier:
  name: testinfra
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
