dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: server-1
    image: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:29093:9093/tcp
    networks:
      - name: "kafka-high-availability"
  - name: server-2
    image: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:29094:9093/tcp
    networks:
      - name: "kafka-high-availability"
  - name: server-3
    image: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:29095:9093/tcp
    networks:
      - name: "kafka-high-availability"
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
verifier:
  name: testinfra
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
