- name: add nginx repository
  ansible.builtin.yum_repository:
    name: nginx
    description: Official nginx yum repository.
    baseurl: "https://nginx.org/packages/rhel/{{ ansible_distribution_major_version }}/$basearch"
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: true
  become: true

- name: install nginx package
  ansible.builtin.dnf:
    name: nginx
    state: present
  become: true
