- name: install python3-rpm package
  ansible.builtin.dnf:
    name: python3-rpm
    state: present
  become: true

- name: gather package facts
  ansible.builtin.package_facts:

- name: ensure firewalld is stopped and disabled
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  when: "'firewalld' in ansible_facts.packages"

- name: install iptables
  ansible.builtin.dnf:
    name: iptables
    state: present
  become: true
