- name: include debian specific tasks
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_os_family | lower == "debian"

- name: include redhat specific tasks
  ansible.builtin.include_tasks: redhat.yaml
  when: ansible_os_family | lower == "redhat"

- name: create tempo group
  ansible.builtin.group:
    name: tempo
    state: present
    system: true
  become: true

- name: create tempo user
  ansible.builtin.user:
    name: tempo
    state: present
    group: tempo
    create_home: false
    shell: /usr/sbin/nologin
    system: true
  become: true

- name: create config directory
  ansible.builtin.file:
    path: "{{ tempo_config_dir }}"
    state: directory
    owner: tempo
    group: tempo
    mode: 0755
  become: true

- name: create storage directory
  ansible.builtin.file:
    path: "{{ tempo_storage_dir }}"
    state: directory
    owner: tempo
    group: tempo
    mode: 0755
  become: true

- name: render systemd service file
  ansible.builtin.template:
    src: tempo.service.j2
    dest: /etc/systemd/system/tempo.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: reload systemd

- name: remove default config file
  ansible.builtin.file:
    path: /etc/tempo/config.yml
    state: absent
  become: true

- name: render config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ tempo_config_dir }}/config.yaml"
    owner: tempo
    group: tempo
    mode: 0644
  become: true
  notify: restart service

- name: ensure service is started and enabled
  ansible.builtin.service:
    name: tempo
    state: started
    enabled: true
  become: true

- name: flush handlers
  ansible.builtin.meta: flush_handlers
