- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  listen: reload systemd

- name: restart node-exporter service
  ansible.builtin.service:
    name: node-exporter
    state: restarted
  become: true
  listen: restart service
