- name: add repostiory gpg key
  ansible.builtin.apt_key:
    url: https://packages.redis.io/gpg
    state: present
  become: true

- name: add repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.redis.io/deb {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  become: true

- name: install redis
  ansible.builtin.apt:
    name: redis-server
    state: present
  become: true
