- name: install packages specific to redhat
  ansible.builtin.dnf:
    name: "{{ admin_redhat_packages }}"
    state: present
  become: true

- name: install common packages
  ansible.builtin.dnf:
    name: "{{ admin_common_packages }}"
    state: present
  become: true

- name: install additional packages
  ansible.builtin.dnf:
    name: "{{ admin_common_additional_packages }}"
    state: present
  become: true
